apiVersion: v1
kind: Service
metadata:
  name: ecuacion-service
spec:
  type: LoadBalancer
  selector:
    app: ecuacion
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30000