apiVersion: apps/v1
kind: Deployment
metadata:
  name: suma-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: suma
  template:
    metadata:
      labels:
        app: suma
    spec:
      containers:
      - name: suma
        image: karencorona/suma-app:local
        imagePullPolicy: Never  # Critical for local testing
        ports:
        - containerPort: 8000